apiVersion: openi.ai/v1
kind: Agent
metadata:
  name: monitoring-agent
  class: DevOpsAgentClass
spec:
  runtime: rust
  image: openi/monitoring-agent:1.0
  inputs:
    - type: metrics
      format: prometheus
  outputs:
    - type: alert
      format: pagerduty
  policies:
    - name: uptime-slo
      action: alert
  permissions:
    - prometheus: read
    - alerting: write
