kind: Deployment
name: healthcare-admin-suite
version: 0.1.0
description: >
  Administrative agent suite for healthcare.
  Includes scheduling, staffing, credentialing, payroll, 
  and capacity management.

agents:
  - path: "manifests/examples/HealthcareAgentClass/Admin/admin-scheduling/AgentManifest.yaml"
  - path: "manifests/examples/HealthcareAgentClass/Admin/admin-staffing/AgentManifest.yaml"
  - path: "manifests/examples/HealthcareAgentClass/Admin/admin-credentialing/AgentManifest.yaml"
  - path: "manifests/examples/HealthcareAgentClass/Admin/admin-payroll/AgentManifest.yaml"
  - path: "manifests/examples/HealthcareAgentClass/Admin/admin-capacity/AgentManifest.yaml"

compliance:
  hipaa: true
  soc2: true
  audit_logging: enabled
  data_retention: "7 years"